#:schema ../../api/generated/word.json
id = "alasa"
author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = "2009"
creator = ["jan Sonja"]
see_also = ["lukin"]
source_language = "Acadian French"
usage_category = "core"
word = "alasa"
deprecated = false

[[audio]]
author = "kala Asi"
link = "https://raw.githubusercontent.com/lipu-linku/ijo/main/kalama/kalaasi2023/alasa.mp3"

[[audio]]
author = "jan Lakuse"
link = "https://raw.githubusercontent.com/lipu-linku/ijo/main/kalama/jlakuse/alasa.mp3"

[[etymology]]
word = "Ã  la chasse"

[ku_data]
catch = 26
chase = 39
collect = 33
explore = 44
finding = 58
gather = 61
hunt = 100
hunting = 87
locate = 38
pursue = 74
pursuit = 75
quest = 33
search = 75
seek = 56
try = 36

[pu_verbatim]
de = "VERB jagen, nach Nahrung suchen"
en = "VERB to hunt, forage"
eo = "VERBO Ä‰asi, kolekti"
fr = "VERBE chasser, cueillir"

[representations]
ligatures = "alasa" # ["alasa"]
ucsur = "U+F1903"
sitelen_emosi = "ğŸ¹"
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/alasa.jpg"
sitelen_jelo = "ğŸ¹" # ["ğŸ¹"]

[usage]
2020-04 = 97
2022-08 = 97
2023-09 = 99

[resources]
sona_pona = "https://sona.pona.la/wiki/alasa"
lipamanka_semantic = "https://lipamanka.gay/essays/dictionary#alasa"
