#:schema ../../api/generated/word.json
id = "ali"
author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
creator = ["jan Sonja"]
see_also = ["ale"]
source_language = "Dutch"
usage_category = "uncommon"
word = "ali"
deprecated = false

[[audio]]
author = "kala Asi"
link = "https://raw.githubusercontent.com/lipu-linku/ijo/main/kalama/kalaasi2023/ali.mp3"

[[audio]]
author = "jan Lakuse"
link = "https://raw.githubusercontent.com/lipu-linku/ijo/main/kalama/jlakuse/ali.mp3"

[[etymology]]
word = "alle"

[ku_data]
all = 32
entire = 27
universe = 21

[representations]
ligatures = "ale" # ["ali"]
ucsur = "U+F1904"
sitelen_emosi = "♾️"
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/ale.jpg"

[usage]
2022-08 = 35
2023-09 = 32

[resources]
sona_pona = "https://sona.pona.la/wiki/ali"

[pu_verbatim]
de = "ADJEKTIV alle, jede/r/s; im Überfluss, zahllos, reichlich\nNOMEN Überfluss, alles, Leben, Universum\nZAHL 100"
en = "ADJECTIVE all; abundant, countless, bountiful, every, plentiful\nNOUN abundance, everything, life, universe\nNUMBER 100"
eo = "ADJEKTIVO ĉiuj; abunda, nenombrebla, ĉiu\nSUBSTANTIVO abundo, ĉio, vivo, universo\nNOMBRO 100"
fr = "ADJECTIF tous, abondants, innombrables\nNOM tout, abondance, la vie, l'univers\nNOMBRE 100"

[toki_inli]
mod = "all, every, abundant, countless, bountiful, plentiful, complete, whole"
n = "abundance, everything, anything, life, the universe"
number = "100"
# Verb ? complete, fill
