#:schema ../../api/generated/word.json
id = "luka"
author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
creator = ["jan Sonja"]
see_also = ["noka"]
source_language = "Serbo-Croatian"
usage_category = "core"
word = "luka"
deprecated = false

[[audio]]
author = "kala Asi"
link = "https://raw.githubusercontent.com/lipu-linku/ijo/main/kalama/kalaasi2023/luka.mp3"

[[audio]]
author = "jan Lakuse"
link = "https://raw.githubusercontent.com/lipu-linku/ijo/main/kalama/jlakuse/luka.mp3"

[[etymology]]
alt = "ruka"
word = "—Ä—É–∫–∞"

[ku_data]
arm = 68
elbow = 25
five = 64
gesture = 27
hand = 100
handful = 29
palm = 32
reach = 25
tap = 26
touch = 33
wrist = 50

[pu_verbatim]
de = "NOMEN Arm, Hand, Tastorgan\nZAHL F√ºnf"
en = "NOUN arm, hand, tactile organ\nNUMBER five"
eo = "SUBSTANTIVO brako, mano, tu≈ùorgano\nNOMBRO kvin"
fr = "NOM bras, main, organe du toucher\nNOMBRE cinq"

[representations]
ligatures = "luka" # ["luka"]
ucsur = "U+F192D"
sitelen_emosi = "‚úã"
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/luka.jpg"
sitelen_jelo = "üñêÔ∏è" # ["üñêÔ∏è"]

[usage]
2022-08 = 99
2023-09 = 100

[resources]
sona_pona = "https://sona.pona.la/wiki/luka"
lipamanka_semantic = "https://lipamanka.gay/essays/dictionary#luka"

[toki_inli]
n = "hand, arm, tactile organ"
vt = "to touch, to pet, to press, to pull, to hold, to hug, to grasp"
number = "5"
