#:schema ../../api/generated/word.json
id = "ma"
author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
creator = ["jan Sonja"]
see_also = []
source_language = "Finnish"
usage_category = "core"
word = "ma"
deprecated = false

[[audio]]
author = "kala Asi"
link = "https://raw.githubusercontent.com/lipu-linku/ijo/main/kalama/kalaasi2023/ma.mp3"

[[audio]]
author = "jan Lakuse"
link = "https://raw.githubusercontent.com/lipu-linku/ijo/main/kalama/jlakuse/ma.mp3"

[[etymology]]
word = "maa"

[ku_data]
acre = 25
area = 81
continent = 40
country = 100
dirt = 33
domain = 45
earth = 71
environment = 54
environmental = 57
field = 80
ground = 64
habitat = 36
kingdom = 28
land = 93
landscape = 40
location = 50
nation = 62
national = 45
nature = 43
outdoors = 38
outside = 26
place = 73
province = 70
realm = 91
region = 80
sector = 31
setting = 40
site = 50
soil = 73
territory = 100
venue = 27
world = 45
yard = 29
zone = 69

[pu_verbatim]
de = "NOMEN Erde (Planet), Land; drauÃŸen, Welt; Land (geo.), Territorium; Erde (Dreck)"
en = "NOUN earth, land; outdoors, world; country, territory; soil"
eo = "SUBSTANTIVO tero, terpeco; eksterdoma subÄ‰iela loko, mondo; lando, Åtato, teritorio; tero (substanco)"
fr = "NOM terre, sol ; monde, lieu en plien air ; pays, territoire"

[representations]
ligatures = "ma" # ["ma"]
ucsur = "U+F1930"
sitelen_emosi = "ğŸï¸"
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/ma.jpg"
sitelen_jelo = "ğŸï¸" # ["ğŸï¸"]

[usage]
2022-08 = 100
2023-09 = 100

[resources]
sona_pona = "https://sona.pona.la/wiki/ma"
lipamanka_semantic = "https://lipamanka.gay/essays/dictionary#ma"

[toki_inli]
n = "earth, land; outdoors, world; country, territory; soil"
