#:schema ../../api/generated/word.json
id = "waso"
author_verbatim = ""
author_verbatim_source = ""
book = "pu"
coined_era = "pre-pu"
coined_year = ""
creator = ["jan Sonja"]
see_also = []
source_language = "Acadian French"
usage_category = "core"
word = "waso"
deprecated = false

[[audio]]
author = "kala Asi"
link = "https://raw.githubusercontent.com/lipu-linku/ijo/main/kalama/kalaasi2023/waso.mp3"

[[audio]]
author = "jan Lakuse"
link = "https://raw.githubusercontent.com/lipu-linku/ijo/main/kalama/jlakuse/waso.mp3"

[[etymology]]
word = "oiseau"

[ku_data]
bat = 23
bird = 100
chicken = 44
duck = 40
eagle = 30
turkey = 33

[pu_verbatim]
de = "NOMEN Vogel, fliegende Kreatur, geflÃ¼geltes Tier"
en = "NOUN bird, flying creature, winged animal"
eo = "SUBSTANTIVO birdo, fluganta vivaÄµo, besto kun flugiloj"
fr = "NOM oiseau, crÃ©ature volante, animal ailÃ©"

[representations]
ligatures = "waso" # ["waso"]
ucsur = "U+F1974"
sitelen_emosi = "ğŸ¦…"
sitelen_sitelen = "https://raw.githubusercontent.com/lipu-linku/ijo/main/sitelensitelen/jonathangabel/waso.jpg"
sitelen_jelo = "ğŸ¦" # ["ğŸ¦"]

[usage]
2022-08 = 99
2023-09 = 99

[resources]
sona_pona = "https://sona.pona.la/wiki/waso"
lipamanka_semantic = "https://lipamanka.gay/essays/dictionary#waso"
